language: java
jdk:
  - openjdk14

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -meonoeek@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="b4dca4d3-2410-4801-9d98-271c167cebe6"