language: java
jdk:
  - openjdk14

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -meonoeek@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="2e3a27e3-5431-4c3d-8a5c-a562570a8c84"